server:
  port: 9000
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/death_tables
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
# App Properties
app:
  jwt:
    secret: SECRET
    token:
      access:
        prefix: "Bearer_"
        expiration: 86400
        header: authorization
      refresh:
        prefix: "Refresh_"
        expiration: 864000
        header: refresh
  default:
    avatar: F:\JavaProjects\deathTables\src\main\resources\static\assets\img\default-avatar.png

loger:
  level:
    root: DEBUG